# Neden NumPy?

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [2]:
ab = []                        

for i in range(0, len(a)):
  ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [5]:
a * b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [6]:
import numpy as np

In [7]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
a = np.array([1,2,3,4,5])

In [9]:
type(a)

numpy.ndarray

In [10]:
np.array([3.14, 4, 2, 13], dtype = "int")

array([ 3,  4,  2, 13])

In [ ]:
#sifirdan array olusturma 

In [9]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
np.random.normal(10, 4, (3,4))

array([[ 7.95311755, 18.88626347,  6.68342754,  9.41779354],
       [ 6.56580837,  9.3286982 ,  2.81822871, 11.70010496],
       [15.3764241 ,  8.20890978,  8.67603323,  5.88175198]])

In [16]:
np.random.randint(0,10, (3,3))

array([[9, 0, 2],
       [1, 1, 2],
       [5, 7, 8]])

# Özellikleri

* **ndim**: _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [30]:
import numpy as np

In [31]:
np.random.randint(10, size = 10)

array([1, 9, 9, 6, 8, 6, 6, 6, 2, 6])

In [32]:
a = np.random.randint(10, size = 10)

In [33]:
a.ndim

1

In [34]:
a.shape

(10,)

In [35]:
a.size

10

In [36]:
a.dtype

dtype('int32')

In [38]:
b = np.random.randint(10, size = (3,5))

In [39]:
b

array([[9, 8, 6, 9, 1],
       [4, 1, 3, 3, 9],
       [9, 9, 4, 0, 7]])

In [40]:
b.ndim

2

In [41]:
b.shape

(3, 5)

In [42]:
b.size

15

In [43]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme (Reshaping)

In [44]:
import numpy as np

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a = np.arange(1,10)

In [48]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a.ndim

1

In [50]:
b = a.reshape((1,9))

In [51]:
b.ndim

2

# Array Birlestirme (Concatenation)

In [52]:
import numpy as np

In [53]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [54]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [55]:
z = np.array([7,8,9])

In [56]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#iki boyut

In [58]:
a = np.array([[1,2,3], 
              [4,5,6]])

In [59]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [10]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma (Splitting)

In [60]:
import numpy as np

In [61]:
x = np.array([1,2,3,99,99,3,2,1])

In [62]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [63]:
a,b,c = np.split(x, [3,5])

In [64]:
a

array([1, 2, 3])

In [65]:
b

array([99, 99])

In [66]:
c

array([3, 2, 1])

In [67]:
#iki boyutlu ayırma

In [68]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [10]:
ust, alt = np.vsplit(m, [2])

In [11]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [15]:
sag, sol = np.hsplit(m, [2])

In [16]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [17]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [1]:
import numpy as np

In [83]:
v = np.array([2,1,4,3,5])

In [84]:
v

array([2, 1, 4, 3, 5])

In [ ]:
np.sort(v)

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

In [ ]:
#iki boyutlu array siralama

In [10]:
m = np.random.normal(20,5, (3,3))

In [11]:
m

array([[25.45684489, 21.83575476, 26.06913773],
       [17.50480621, 18.65456644, 25.99114299],
       [15.28755765, 21.08674903, 16.10947821]])

In [12]:
np.sort(m, axis = 1)

array([[21.83575476, 25.45684489, 26.06913773],
       [17.50480621, 18.65456644, 25.99114299],
       [15.28755765, 16.10947821, 21.08674903]])

In [13]:
np.sort(m, axis = 0)

array([[15.28755765, 18.65456644, 16.10947821],
       [17.50480621, 21.08674903, 25.99114299],
       [25.45684489, 21.83575476, 26.06913773]])

# Index ile Elemanlara Erişmek

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([9, 7, 0, 1, 1, 3, 5, 9, 6, 8])

In [ ]:
a[0]

In [3]:
a[-1]

8

In [4]:
a[0] = 100

In [5]:
a

array([100,   7,   0,   1,   1,   3,   5,   9,   6,   8])

In [80]:
m = np.random.randint(10, size = (3,5))
m

array([[7, 9, 9, 6, 1],
       [7, 2, 4, 2, 9],
       [4, 0, 0, 6, 3]])

In [8]:
m[0,0]

6

In [9]:
m[1,1]

3

In [10]:
m[1, 4]

9

In [11]:
m[1, 4] = 99

In [12]:
m

array([[ 6,  8,  8,  1,  9],
       [ 5,  3,  6,  5, 99],
       [ 5,  8,  4,  1,  4]])

In [13]:
m[1,4] = 2.2

In [14]:
m

array([[6, 8, 8, 1, 9],
       [5, 3, 6, 5, 2],
       [5, 8, 4, 1, 4]])

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [72]:
a[0:3]

array([20, 21, 22])

In [73]:
a[:3]

array([20, 21, 22])

In [74]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [6]:
a[1::2]

array([21, 23, 25, 27, 29])

In [7]:
a[0::2]

array([20, 22, 24, 26, 28])

In [8]:
a[2::2]

array([22, 24, 26, 28])

In [9]:
a[0::3]

array([20, 23, 26, 29])

In [ ]:
#iki boyutlu slice islemleri

In [10]:
m = np.random.randint(10, size = (5,5))

In [11]:
m

array([[4, 9, 9, 8, 7],
       [0, 4, 7, 4, 5],
       [8, 2, 7, 6, 3],
       [3, 3, 8, 8, 1],
       [6, 4, 0, 5, 0]])

In [12]:
m[:,0]

array([4, 0, 8, 3, 6])

In [13]:
m[:,1]

array([9, 4, 2, 3, 4])

In [14]:
m[:,4]

array([7, 5, 3, 1, 0])

In [16]:
m

array([[4, 9, 9, 8, 7],
       [0, 4, 7, 4, 5],
       [8, 2, 7, 6, 3],
       [3, 3, 8, 8, 1],
       [6, 4, 0, 5, 0]])

In [15]:
m[0,:]

array([4, 9, 9, 8, 7])

In [17]:
m[0]

array([4, 9, 9, 8, 7])

In [18]:
m[1,:]

array([0, 4, 7, 4, 5])

In [19]:
m[0:2, 0:3]

array([[4, 9, 9],
       [0, 4, 7]])

In [22]:
m[:,0:2]

array([[4, 9],
       [0, 4],
       [8, 2],
       [3, 3],
       [6, 4]])

In [24]:
m

array([[4, 9, 9, 8, 7],
       [0, 4, 7, 4, 5],
       [8, 2, 7, 6, 3],
       [3, 3, 8, 8, 1],
       [6, 4, 0, 5, 0]])

In [23]:
m[1:3, 0:2]

array([[0, 4],
       [8, 2]])

# Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np
a = np.random.randint(10, size = (5, 5))
a

array([[1, 2, 1, 2, 8],
       [3, 9, 2, 4, 9],
       [7, 3, 5, 1, 3],
       [6, 1, 0, 6, 8],
       [2, 7, 9, 9, 1]])

In [2]:
alt_a = a[0:3, 0:2]
alt_a

array([[1, 2],
       [3, 9],
       [7, 3]])

In [4]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [5]:
alt_a

array([[99999,     2],
       [    3,   888],
       [    7,     3]])

In [6]:
a

array([[99999,     2,     1,     2,     8],
       [    3,   888,     2,     4,     9],
       [    7,     3,     5,     1,     3],
       [    6,     1,     0,     6,     8],
       [    2,     7,     9,     9,     1]])

In [7]:
m = np.random.randint(10, size = (5, 5))
m

array([[0, 5, 2, 6, 8],
       [1, 7, 8, 7, 7],
       [3, 2, 1, 1, 9],
       [5, 0, 9, 2, 8],
       [4, 4, 6, 0, 7]])

In [8]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[0, 5],
       [1, 7],
       [3, 2]])

In [9]:
alt_b[0,0] = 9999

In [10]:
alt_b

array([[9999,    5],
       [   1,    7],
       [   3,    2]])

In [11]:
m

array([[0, 5, 2, 6, 8],
       [1, 7, 8, 7, 7],
       [3, 2, 1, 1, 9],
       [5, 0, 9, 2, 8],
       [4, 4, 6, 0, 7]])

# Fancy Index ile Elemanlara Erişmek

In [3]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
v[1]

3

In [5]:
v[3]

9

In [6]:
v[5]

15

In [7]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [8]:
al_getir = [1,3,5]

In [9]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
v[al_getir]

array([ 3,  9, 15])

In [11]:
#iki boyutta fancy

In [12]:
m = np.arange(9).reshape((3,3))

In [13]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [12]:
m[satir, sutun]

array([1, 5])

In [ ]:
#basit index ile fancy index

In [13]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
m[2, [1,2]]

array([7, 8])

In [ ]:
#slice ile fancy

In [15]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [16]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [17]:
v < 3

array([ True,  True, False, False, False])

In [18]:
v[v < 3]

array([1, 2])

In [19]:
v[v > 3]

array([4, 5])

In [6]:
v[v >= 3]

array([3, 4, 5])

In [7]:
v[v <= 3]

array([1, 2, 3])

In [8]:
v[v == 3]

array([3])

In [9]:
v[v != 3]

array([1, 2, 4, 5])

In [10]:
v

array([1, 2, 3, 4, 5])

In [11]:
v * 2

array([ 2,  4,  6,  8, 10])

In [12]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [13]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [14]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [20]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [21]:
v - 1

array([0, 1, 2, 3, 4])

In [22]:
v * 5

array([ 5, 10, 15, 20, 25])

In [23]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [24]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [25]:
#ufunc

In [26]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [7]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [8]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [9]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [10]:
v**2

array([ 1,  4,  9, 16, 25])

In [11]:
v**3

array([  1,   8,  27,  64, 125])

In [12]:
np.power(v, 3)

array([  1,   8,  27,  64, 125])

In [13]:
v % 2

array([1, 0, 1, 0, 1])

In [14]:
np.mod(v, 2)

array([1, 0, 1, 0, 1])

In [16]:
np.absolute(np.array([-3]))

array([3])

In [20]:
np.sin(360)

0.9589157234143065

In [21]:
np.cos(180)

-0.5984600690578581

In [22]:
v = np.array([1,2,3])

In [23]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [25]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [26]:
?np

Type:        module
String form: <module 'numpy' from '/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        /anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

U

In [ ]:
#cheatsheet

# İstatistiksel Hesaplamalar

In [28]:
v

array([1, 2, 3])

In [29]:
np.mean(v)

2.0

In [30]:
v.sum()

6

In [31]:
v.min()

1

* np.mean(arr,axis=0) | Returns mean along specific axis

* arr.sum() | Returns sum of arr

* arr.min() | Returns minimum value of arr

* arr.max(axis=0) | Returns maximum value of specific axis

* np.var(arr) | Returns the variance of array

* np.std(arr,axis=1) | Returns the standard deviation of specific axis

* arr.corrcoef() | Returns correlation coefficient of array

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [2]:
import numpy as np

**5 * x0 + x1 = 12  
x0 + 3 * x1 = 10**

In [3]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [4]:
a

array([[5, 1],
       [1, 3]])

In [5]:
b

array([12, 10])

In [6]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

# BOLUM SONU DEGERLENDIRMESI

In [29]:
a=np.array([[4, 0, 3, 0, 1],

            [9, 6, 1, 5, 9],

            [1, 9, 0, 8, 2]])

# Pandas Serisi Oluşturmak

In [1]:
import pandas as pd 

In [3]:
pd.Series([10,88,3,4,5])

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [4]:
seri = pd.Series([10,88,3,4,5])

In [5]:
type(seri)

pandas.core.series.Series

In [6]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [7]:
seri.dtype 

dtype('int64')

In [8]:
seri.size

5

In [9]:
seri.ndim

1

In [10]:
seri.values

array([10, 88,  3,  4,  5])

In [12]:
seri.head(3)

0    10
1    88
2     3
dtype: int64

In [13]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

In [ ]:
#index isimlendirmesi

In [14]:
pd.Series([99,22,332,94,5])

0     99
1     22
2    332
3     94
4      5
dtype: int64

In [15]:
pd.Series([99,22,332,94,5], index = [1,3,5,7,9])

1     99
3     22
5    332
7     94
9      5
dtype: int64

In [16]:
pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

a     99
b     22
c    332
d     94
e      5
dtype: int64

In [17]:
seri = pd.Series([99,22,332,94,5], index = ["a","b","c","d","e"])

In [18]:
seri["a"]

99

In [19]:
seri["a":"c"]

a     99
b     22
c    332
dtype: int64

In [ ]:
#sozluk uzerinden liste olusturmak

In [23]:
sozluk = {"reg":10, "log":11, "cart": 12}

In [24]:
seri = pd.Series(sozluk)

In [25]:
seri

reg     10
log     11
cart    12
dtype: int64

In [ ]:
#iki seriyi birlestirerek seri olusturma

In [26]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

# Eleman İşlemleri

In [27]:
import numpy as np
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int64

In [28]:
seri[0]

1

In [29]:
seri[0:3]

0     1
1     2
2    33
dtype: int64

In [31]:
seri = pd.Series([121,200,150,99], 
                 index = ["reg","loj","cart","rf"])

In [32]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [33]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [34]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [35]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [36]:
seri.values

array([121, 200, 150,  99])

In [ ]:
#eleman sorgulama

In [37]:
"reg" in seri

True

In [38]:
"a" in seri

False

In [39]:
seri["reg"]

121

In [ ]:
#fancy eleman

In [40]:
seri[["rf", "reg"]]

rf      99
reg    121
dtype: int64

In [42]:
seri["reg"] = 130

In [43]:
seri["reg"]

130

In [44]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

# Pandas DataFrame Oluşturma

In [6]:
import pandas as pd

In [7]:
l = [1,2,39,67,90]

In [8]:
l

[1, 2, 39, 67, 90]

In [9]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [10]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [12]:
#df isimlendirme

In [13]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [14]:
df.columns = ("deg1","deg2","deg3")

In [15]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [18]:
df.shape

(3, 3)

In [19]:
df.ndim

2

In [20]:
df.size

9

In [21]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
type(df.values)

numpy.ndarray

In [23]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [24]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [25]:
a = np.array([1,2,3,4,5])

In [26]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

# Eleman İşlemleri

In [27]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [28]:
sozluk = {"var1": s1, "var2": s2, "var3": s3}

In [29]:
sozluk

{'var1': array([6, 4, 2, 6, 2]),
 'var2': array([5, 7, 0, 2, 3]),
 'var3': array([9, 6, 7, 5, 3])}

In [30]:
df = pd.DataFrame(sozluk)

In [31]:
df

var1  var2  var3
0     6     5     9
1     4     7     6
2     2     0     7
3     6     2     5
4     2     3     3

In [32]:
df[0:1]

var1  var2  var3
0     6     5     9

In [33]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [34]:
df.index = ["a","b","c","d","e"]

In [35]:
df

var1  var2  var3
a     6     5     9
b     4     7     6
c     2     0     7
d     6     2     5
e     2     3     3

In [36]:
df["c":"e"]

var1  var2  var3
c     2     0     7
d     6     2     5
e     2     3     3

In [37]:
#silme

In [38]:
df.drop("a", axis = 0)

var1  var2  var3
b     4     7     6
c     2     0     7
d     6     2     5
e     2     3     3

In [39]:
df

var1  var2  var3
a     6     5     9
b     4     7     6
c     2     0     7
d     6     2     5
e     2     3     3

In [38]:
df.drop("a", axis = 0, inplace = True)

In [39]:
df

var1  var2  var3
b     3     7     6
c     3     2     6
d     4     9     8
e     5     0     9

In [ ]:
#fancy 

In [40]:
l = ["c","e"]

In [41]:
df.drop(l, axis = 0)

var1  var2  var3
b     3     7     6
d     4     9     8

In [ ]:
#degiskenler icin

In [43]:
df

var1  var2  var3
b     3     7     6
c     3     2     6
d     4     9     8
e     5     0     9

In [42]:
"var1" in df

True

In [44]:
l = ["var1","var4","var2"]

In [45]:
for i in l:
    print(i in df)

True
False
True


In [50]:
df

var1  var2  var3
b     7     7     6
c     2     2     6
d     9     9     8
e     0     0     9

In [51]:
df["var1"]

b    7
c    2
d    9
e    0
Name: var1, dtype: int64

In [52]:
df["var4"] = df["var1"] / df["var2"]

In [53]:
df

var1  var2  var3  var4
b     7     7     6   1.0
c     2     2     6   1.0
d     9     9     8   1.0
e     0     0     9   NaN

In [ ]:
#degisken silmek

In [54]:
df.drop("var4", axis = 1)

var1  var2  var3
b     7     7     6
c     2     2     6
d     9     9     8
e     0     0     9

In [55]:
df

var1  var2  var3  var4
b     7     7     6   1.0
c     2     2     6   1.0
d     9     9     8   1.0
e     0     0     9   NaN

In [56]:
df.drop("var4", axis = 1, inplace = True)

In [57]:
df

var1  var2  var3
b     7     7     6
c     2     2     6
d     9     9     8
e     0     0     9

In [58]:
l = ["var1","var2"]

In [59]:
df.drop(l, axis = 1)

var3
b     6
c     6
d     8
e     9

# Gözlem ve Değişken Seçimi: loc & iloc

In [40]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0     8    24    13
1    13    17    21
2    10    29    12
3     3    18    28
4     3     2     3
5     3     2    27
6     6    17    11
7    27    13    20
8    23    12    18
9     7    22    13

In [ ]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.

In [3]:
df.loc[0:3]

var1  var2  var3
0    19    25     1
1     1     2    10
2    12    11     6
3    18    10    18

In [ ]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar.

In [4]:
df.iloc[0:3]

var1  var2  var3
0    19    25     1
1     1     2    10
2    12    11     6

In [5]:
df.iloc[0,0]

19

In [7]:
df

var1  var2  var3
0    19    25     1
1     1     2    10
2    12    11     6
3    18    10    18
4    17    11    27
5     8    20    21
6     9    13     7
7    19    24     9
8    27    13    29
9    18    10    23

In [6]:
df.iloc[:3,:2]

var1  var2
0    19    25
1     1     2
2    12    11

In [8]:
df.loc[0:3, "var3"]

0     1
1    10
2     6
3    18
Name: var3, dtype: int64

In [10]:
df.loc[0:3, "var3"]

0     1
1    10
2     6
3    18
Name: var3, dtype: int64

In [13]:
df.iloc[0:3]["var3"]

0     1
1    10
2     6
Name: var3, dtype: int64

# Koşullu Eleman İşlemleri

In [1]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df

var1  var2  var3
0    24    10     2
1    21     8     6
2     8     5    15
3    21    21    11
4    21    20    15
5    29     2     1
6    13    25     7
7    15     1    12
8    13    25    19
9    26    18    17

In [2]:
df["var1"]

0    24
1    21
2     8
3    21
4    21
5    29
6    13
7    15
8    13
9    26
Name: var1, dtype: int32

In [3]:
df[0:2][["var1","var2"]]

var1  var2
0    24    10
1    21     8

In [4]:
df

var1  var2  var3
0    24    10     2
1    21     8     6
2     8     5    15
3    21    21    11
4    21    20    15
5    29     2     1
6    13    25     7
7    15     1    12
8    13    25    19
9    26    18    17

In [5]:
df.var1

0    24
1    21
2     8
3    21
4    21
5    29
6    13
7    15
8    13
9    26
Name: var1, dtype: int32

In [6]:
df[df.var1 > 15]

var1  var2  var3
0    24    10     2
1    21     8     6
3    21    21    11
4    21    20    15
5    29     2     1
9    26    18    17

In [7]:
df[(df.var1 > 15) & (df.var3 < 5)]

var1  var2  var3
0    24    10     2
5    29     2     1

In [8]:
df.loc[(df.var1 > 15), ["var1","var2"]]

var1  var2
0    24    10
1    21     8
3    21    21
4    21    20
5    29     2
9    26    18

In [9]:
df[(df.var1 > 15)][["var1","var2"]]

var1  var2
0    24    10
1    21     8
3    21    21
4    21    20
5    29     2
9    26    18

# Birleştirme (Join) İşlemleri

In [10]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    29     6    20
1    27     8    16
2     9     2     6
3    27    29    25
4     1    17    22

In [11]:
df2 = df1 + 99

In [25]:
df2

var1  var2  var3
0   123   124   108
1   115   100   118
2   119   111   115
3   110   102   103
4   100   122   101

In [26]:
pd.concat([df1,df2])

var1  var2  var3
0    24    25     9
1    16     1    19
2    20    12    16
3    11     3     4
4     1    23     2
0   123   124   108
1   115   100   118
2   119   111   115
3   110   102   103
4   100   122   101

In [28]:
?pd.concat

Signature:
pd.concat(
    objs,
    axis=0,
    join='outer',
    join_axes=None,
    ignore_index=False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity=False,
    sort=None,
    copy=True,
)
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series, DataFrame, or Panel objects
    If a dict is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes o

In [30]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0    24    25     9
1    16     1    19
2    20    12    16
3    11     3     4
4     1    23     2
5   123   124   108
6   115   100   118
7   119   111   115
8   110   102   103
9   100   122   101

In [34]:
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [35]:
df2.columns = ["var1","var2","deg3"]

In [36]:
df2

var1  var2  deg3
0   123   124   108
1   115   100   118
2   119   111   115
3   110   102   103
4   100   122   101

In [37]:
df1

var1  var2  var3
0    24    25     9
1    16     1    19
2    20    12    16
3    11     3     4
4     1    23     2

In [38]:
pd.concat([df1, df2])

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


deg3  var1  var2  var3
0    NaN    24    25   9.0
1    NaN    16     1  19.0
2    NaN    20    12  16.0
3    NaN    11     3   4.0
4    NaN     1    23   2.0
0  108.0   123   124   NaN
1  118.0   115   100   NaN
2  115.0   119   111   NaN
3  103.0   110   102   NaN
4  101.0   100   122   NaN

In [39]:
pd.concat([df1, df2], join = "inner")

var1  var2
0    24    25
1    16     1
2    20    12
3    11     3
4     1    23
0   123   124
1   115   100
2   119   111
3   110   102
4   100   122

In [42]:
pd.concat([df1, df2], join_axes = [df2.columns], ignore_index=True)

var1  var2   deg3
0    24    25    NaN
1    16     1    NaN
2    20    12    NaN
3    11     3    NaN
4     1    23    NaN
5   123   124  108.0
6   115   100  118.0
7   119   111  115.0
8   110   102  103.0
9   100   122  101.0

# İleri Birleştirme İşlemleri

In [1]:
import pandas as pd

In [ ]:
#birebir birlestirme

In [2]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [3]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})

df2

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [4]:
pd.merge(df1, df2)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [5]:
pd.merge(df1, df2, on = "calisanlar")

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [ ]:
#coktan teke 

In [6]:
df3 = pd.merge(df1, df2)

In [7]:
df3

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [8]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})

df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [9]:
pd.merge(df3,df4)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [ ]:
# çoktan çoka

In [10]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [11]:
df1

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [12]:
pd.merge(df1, df5)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [12]:
import seaborn as sns

In [13]:
?sns.load_dataset

In [14]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [15]:
df.shape

(1035, 6)

In [16]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [17]:
df["mass"].mean()

2.6381605847953233

In [18]:
df["mass"].count()

513

In [19]:
df["mass"].min()

0.0036

In [22]:
df["mass"].max()
df.mass.max()

25.0

In [21]:
df["mass"].sum()

1353.37638

In [30]:
df["mass"].std()

3.8186166509616046

In [31]:
df["mass"].var()

14.58183312700122

In [25]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [34]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

# Gruplama İşlemleri

In [31]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [32]:
df.groupby("gruplar")

In [33]:
df.groupby("gruplar").mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [34]:
df.groupby("gruplar").sum()

veri
gruplar      
A          33
B          54
C         107

In [35]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [36]:
df.groupby("method")

In [38]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [39]:
df.groupby("method")["orbital_period"].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

# İleri Toplulaştırma İşlemleri (Aggregate, filter, transform, apply)

In [40]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [41]:
#aggregate

In [42]:
df.groupby("gruplar").mean()

degisken1  degisken2
gruplar                      
A               16        181
B               17        182
C               66        651

In [43]:
df.groupby("gruplar").aggregate([min, np.median, max])

degisken1            degisken2            
              min median max       min median  max
gruplar                                           
A              10     16  22       100    181  262
B              11     17  23       111    182  253
C              33     66  99       333    651  969

In [44]:
df.groupby("gruplar").aggregate({"degisken1": "min", "degisken2": "max"})

degisken1  degisken2
gruplar                      
A               10        262
B               11        253
C               33        969

In [45]:
#filter

In [46]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [47]:
def filter_func(x):
    return x["degisken1"].std() > 9

In [4]:
df.groupby("gruplar").std()

degisken1   degisken2
gruplar                       
A         8.485281  114.551299
B         8.485281  100.409163
C        46.669048  449.719913

In [3]:
df.groupby("gruplar").filter(filter_func)

gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [54]:
df.groupby("gruplar").aggregate({"degisken1":"std"})

degisken1
gruplar           
A         8.485281
B         8.485281
C        46.669048

In [49]:
#transform

In [1]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [2]:
df["degisken1"]*9

0     90
1    207
2    297
3    198
4     99
5    891
Name: degisken1, dtype: int64

In [7]:
df_a = df.iloc[:,1:3]

In [11]:
df_a.transform(lambda x: (x-x.mean()) / x.std())

degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

In [ ]:
#apply

In [5]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [3]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [4]:
df.apply(np.mean)

degisken1     33.0
degisken2    338.0
dtype: float64

In [7]:
df.groupby("gruplar").apply(np.mean)

degisken1  degisken2
gruplar                      
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

# Pivot Tablolar

In [1]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [7]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [ ]:
#pivot ile table

In [9]:
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [11]:
titanic.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [12]:
age = pd.cut(titanic["age"], [0, 18, 90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64]): [(0, 18] < (18, 90]]

In [17]:
titanic.pivot_table("survived", ["sex", age], "class")

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

# Dış Kaynaklı Veri Okumak

In [1]:
import pandas as pd

In [2]:
?pd.read_csv

In [6]:
df =pd.read_csv("reading_data/ornekcsv.csv",sep=";")
df.dropna()

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [3]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [18]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2 
6   8 2
7   9 2
8  10 2

In [19]:
#excel
pd.read_excel("reading_data/ornekx.xlsx")

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [8]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.head()

a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [12]:
df.columns = ("A","B","C")

In [13]:
df

A    B     C
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [14]:
#sıfırdan txt okuma
tips = pd.read_csv("reading_data/data.txt")

In [15]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# Bonus: Problem Çözme ve Döküman Okuma Kültürü

In [16]:
9 / 0

ZeroDivisionError: division by zero

# BOLUM SONU DEGERLENDIRMESI